// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-BbSiwGb7zwvkUzoDZtMpr3plgHvT5E',
    appId: '1:945237171729:web:197d9370114b5f2e8f1bb0',
    messagingSenderId: '945237171729',
    projectId: 'joinx-instagram-clone',
    authDomain: 'joinx-instagram-clone.firebaseapp.com',
    storageBucket: 'joinx-instagram-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4CSR3U6LEe5HeBP3Kklzfy2g7aN4-8Ps',
    appId: '1:945237171729:android:6c9b8dc9b47919898f1bb0',
    messagingSenderId: '945237171729',
    projectId: 'joinx-instagram-clone',
    storageBucket: 'joinx-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcvsAUGOgQY97jORtzHYvYX78RcEfWOU',
    appId: '1:945237171729:ios:15be644304dcaba28f1bb0',
    messagingSenderId: '945237171729',
    projectId: 'joinx-instagram-clone',
    storageBucket: 'joinx-instagram-clone.appspot.com',
    iosClientId: '945237171729-tq6u9m76usm2uqs4v02enb161hq4tffj.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
